### ISSUE TITLE
no deletes after upgrade atom 1.52.0 x64

### ISSUE THREAD

**Issue by RezzZ** [olmokramer/atom-permanent-delete#16]
I updated to 1.52.0 and files/folders are no longer being removed. Not sure if it is related to the upgrade but is hard to ignore. More people troubles with deleting files?

**Comment by cratown** [comment]
Same here, there already is pull request with fix: https://github.com/zorn-v/atom-permanent-delete/pull/15

**Comment by zorn-v** [comment]
Fixed in v0.1.8
